from django.urls import path
from .views import LoginView, UserInfoView, SetRoleView, CaptchaView, dashboard, MemberListView, MemberDetailView, UserGroupListView, UserGroupDetailView, AgentListCreateView, AgentRetrieveUpdateDestroyView, ModelApiListCreateView, ModelApiRetrieveUpdateDestroyView, refresh_usage, TokenUsageListCreateView, token_usage_stats, KnowledgeBaseListCreateView, KnowledgeBaseRetrieveUpdateDestroyView, SpaceListCreateView, SpaceRetrieveUpdateDestroyView, SpaceMemberListCreateView, SpaceMemberRetrieveUpdateDestroyView, SpaceDocumentListCreateView, SpaceDocumentRetrieveUpdateDestroyView, KnowledgeFileProcessView, KnowledgeFileUploadView

urlpatterns = [
    path('login/', LoginView.as_view()),
    path('userinfo/', UserInfoView.as_view()),
    path('set_role/', SetRoleView.as_view()),
    path('captcha/', CaptchaView.as_view()),
    path('dashboard/', dashboard, name='dashboard'),
    path('users/', MemberListView.as_view(), name='member-list'),
    path('users/<int:id>/', MemberDetailView.as_view(), name='member-detail'),
    path('users/groups/', UserGroupListView.as_view(), name='group-list'),
    path('users/groups/<int:id>/', UserGroupDetailView.as_view(), name='group-detail'),
    path('agents/', AgentListCreateView.as_view(), name='agent-list'),
    path('agents/<int:id>/', AgentRetrieveUpdateDestroyView.as_view(), name='agent-detail'),
    path('modelapis/', ModelApiListCreateView.as_view(), name='modelapi-list'),
    path('modelapis/<int:id>/', ModelApiRetrieveUpdateDestroyView.as_view(), name='modelapi-detail'),
    path('modelapis/refresh_usage/', refresh_usage, name='modelapi-refresh-usage'),
    path('tokenusages/', TokenUsageListCreateView.as_view(), name='tokenusage-list'),
    path('tokenusages/stats/', token_usage_stats, name='tokenusage-stats'),
    path('knowledgebases/', KnowledgeBaseListCreateView.as_view(), name='knowledgebase-list'),
    path('knowledgebases/<int:id>/', KnowledgeBaseRetrieveUpdateDestroyView.as_view(), name='knowledgebase-detail'),
    path('spaces/', SpaceListCreateView.as_view(), name='space-list'),
    path('spaces/<int:id>/', SpaceRetrieveUpdateDestroyView.as_view(), name='space-detail'),
    path('spaces/<int:space_id>/members/', SpaceMemberListCreateView.as_view(), name='space-member-list'),
    path('spaces/<int:space_id>/members/<int:id>/', SpaceMemberRetrieveUpdateDestroyView.as_view(), name='space-member-detail'),
    path('spaces/<int:space_id>/documents/', SpaceDocumentListCreateView.as_view(), name='space-document-list'),
    path('spaces/<int:space_id>/documents/<int:id>/', SpaceDocumentRetrieveUpdateDestroyView.as_view(), name='space-document-detail'),
    path('knowledgebases/files/<int:file_id>/process/', KnowledgeFileProcessView.as_view(), name='knowledge_file_process'),
    path('knowledgefiles/', KnowledgeFileUploadView.as_view(), name='knowledgefile-upload'),
] 