# Generated by Django 4.2.22 on 2025-06-08 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='用户组名')),
                ('modules', models.JSONField(default=list, verbose_name='功能模块')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('description', models.TextField(blank=True, null=True, verbose_name='备注说明')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='api_key',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='API-key'),
        ),
        migrations.AddField(
            model_name='user',
            name='token_usage',
            field=models.BigIntegerField(default=0, verbose_name='token用量'),
        ),
        migrations.AddField(
            model_name='user',
            name='valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='有效期'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', '学生'), ('teacher', '老师'), ('admin', '教务'), ('sysadmin', '系统管理员')], default='student', max_length=32, verbose_name='角色'),
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.usergroup', verbose_name='所属用户组'),
        ),
    ]
