# Generated by Django 4.2.22 on 2025-06-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usergroup_user_api_key_user_token_usage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='智能体名称')),
                ('apikey', models.CharField(max_length=128, unique=True, verbose_name='API-key')),
                ('role', models.CharField(max_length=128, verbose_name='可用角色')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
