# Generated by Django 4.2.22 on 2025-06-09 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_modelapi'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apikey', models.CharField(max_length=128, verbose_name='API-key')),
                ('tokens', models.IntegerField(verbose_name='消耗token数')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='调用时间')),
                ('prompt', models.TextField(blank=True, null=True, verbose_name='请求内容摘要')),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.agent', verbose_name='智能体')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
    ]
