# Generated by Django 4.2.22 on 2025-06-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_space_spacedocument_spacemember'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelapi',
            name='base_url',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Base URL'),
        ),
        migrations.AddField(
            model_name='modelapi',
            name='model_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Model Name'),
        ),
    ]
