# Generated by Django 4.2.22 on 2025-06-14 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_modelapi_base_url_modelapi_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgefile',
            name='status',
            field=models.CharField(default='pending', max_length=16, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='user',
            name='api_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='API Key'),
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('chunk_index', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='users.knowledgefile')),
            ],
        ),
    ]
