# Generated by Django 4.2.22 on 2025-06-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_knowledgefile_status_alter_user_api_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgefile',
            name='status',
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='user',
            name='api_key',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='API-key'),
        ),
        migrations.DeleteModel(
            name='KnowledgeChunk',
        ),
    ]
