# Generated by Django 4.2.22 on 2025-06-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_knowledgefile_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deepseek_api_key',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Deepseek API Key'),
        ),
        migrations.AddField(
            model_name='user',
            name='openai_api_key',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='OpenAI API Key'),
        ),
        migrations.AlterField(
            model_name='user',
            name='api_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='API Key'),
        ),
    ]
