# Generated by Django 4.2.22 on 2025-06-14 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_modelapi_apikey'),
        ('users', '0012_remove_modelapi_apikey_unique'),
    ]

    operations = [
    ]
