# Generated by Django 4.2.22 on 2025-06-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_merge_20250614_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelapi',
            name='apikey',
            field=models.CharField(max_length=256, verbose_name='API-key'),
        ),
    ]
