# Generated by Django 4.2.22 on 2025-06-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_modelapi_apikey_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgefile',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='是否归档'),
        ),
    ]
