# Generated by Django 4.2.22 on 2025-06-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_add_archived_to_knowledgefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgefile',
            name='char_count',
            field=models.IntegerField(default=0, verbose_name='字符数'),
        ),
    ]
