# Generated by Django 4.2.22 on 2025-06-14 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_add_char_count_to_knowledgefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgefile',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='knowledgefile',
            name='char_count',
        ),
    ]
