# Generated by Django 4.2.22 on 2025-06-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_knowledgefile_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgefile',
            name='char_count',
            field=models.IntegerField(default=0, verbose_name='字符数'),
        ),
    ]
