# Generated by Django 4.2.22 on 2025-06-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_knowledgefile_char_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='embedding_config',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='分段与向量化配置'),
        ),
    ]
